import { Category, Style } from '@/types';

export const categories: Category[] = [
  { id: 'box-braids', name: 'Box Braids' },
  { id: 'knotless', name: 'Knotless Braids' },
  { id: 'ghana-fulani', name: 'Ghana & Fulani' },
  { id: 'cornrows', name: 'Cornrows' },
  { id: 'twists', name: 'Twists' },
  { id: 'locs', name: 'Locs' },
  { id: 'goddess-protective', name: 'Goddess & Protective' },
  { id: 'cultural-specialty', name: 'Cultural & Specialty' },
];

export const styles: Style[] = [
  // BOX BRAIDS
  {
    id: 1,
    name: 'Classic Box Braids',
    category: 'Box Braids',
    length: 'Long',
    price: 180,
    duration: '4-5 hrs',
    rating: 4.8,
    reviews: 127,
    image: '/assets/img/style-1.jpg',
    popularity: 95,
  },
  {
    id: 2,
    name: 'Extra Long Box Braids',
    category: 'Box Braids',
    length: 'Extra Long',
    price: 250,
    duration: '6-7 hrs',
    rating: 4.9,
    reviews: 89,
    image: '/assets/img/style-2.jpg',
    popularity: 88,
    isTrending: true,
  },
  {
    id: 3,
    name: 'Jumbo Box Braids',
    category: 'Box Braids',
    length: 'Long',
    price: 200,
    duration: '3-4 hrs',
    rating: 4.7,
    reviews: 156,
    image: '/assets/img/style-3.jpg',
    popularity: 82,
  },
  {
    id: 4,
    name: 'Medium Box Braids',
    category: 'Box Braids',
    length: 'Medium',
    price: 160,
    duration: '4-5 hrs',
    rating: 4.6,
    reviews: 98,
    image: '/assets/img/style-4.jpg',
    popularity: 78,
  },

  // KNOTLESS BRAIDS
  {
    id: 5,
    name: 'Sleek Knotless Braids',
    category: 'Knotless Braids',
    length: 'Long',
    price: 220,
    duration: '5-6 hrs',
    rating: 4.9,
    reviews: 203,
    image: '/assets/img/style-5.jpg',
    popularity: 98,
    isTrending: true,
    isNew: true,
  },
  {
    id: 6,
    name: 'Goddess Knotless',
    category: 'Knotless Braids',
    length: 'Long',
    price: 240,
    duration: '5-6 hrs',
    rating: 4.9,
    reviews: 178,
    image: '/assets/img/style-6.jpg',
    popularity: 92,
    isNew: true,
  },
  {
    id: 7,
    name: 'Half-Up Knotless',
    category: 'Knotless Braids',
    length: 'Medium',
    price: 190,
    duration: '4-5 hrs',
    rating: 4.8,
    reviews: 145,
    image: '/assets/img/style-7.jpg',
    popularity: 86,
  },
  {
    id: 8,
    name: 'Small Knotless',
    category: 'Knotless Braids',
    length: 'Extra Long',
    price: 280,
    duration: '7-8 hrs',
    rating: 4.7,
    reviews: 112,
    image: '/assets/img/style-8.jpg',
    popularity: 84,
    isTrending: true,
  },

  // GHANA & FULANI
  {
    id: 9,
    name: 'Ghana Braids',
    category: 'Ghana & Fulani',
    length: 'Long',
    price: 200,
    duration: '4-5 hrs',
    rating: 4.8,
    reviews: 134,
    image: '/assets/img/style-9.jpg',
    popularity: 86,
  },
  {
    id: 10,
    name: 'Fulani Braids',
    category: 'Ghana & Fulani',
    length: 'Medium',
    price: 190,
    duration: '4-5 hrs',
    rating: 4.7,
    reviews: 112,
    image: '/assets/img/style-10.jpg',
    popularity: 82,
  },
  {
    id: 11,
    name: 'Ghana Cornrows',
    category: 'Ghana & Fulani',
    length: 'Long',
    price: 210,
    duration: '4-5 hrs',
    rating: 4.8,
    reviews: 98,
    image: '/assets/img/style-11.jpg',
    popularity: 80,
    isTrending: true,
  },

  // CORNROWS
  {
    id: 12,
    name: 'Classic Cornrows',
    category: 'Cornrows',
    length: 'Short',
    price: 120,
    duration: '2-3 hrs',
    rating: 4.5,
    reviews: 89,
    image: '/assets/img/style-12.jpg',
    popularity: 75,
  },
  {
    id: 13,
    name: 'Feed-in Cornrows',
    category: 'Cornrows',
    length: 'Medium',
    price: 160,
    duration: '3-4 hrs',
    rating: 4.7,
    reviews: 134,
    image: '/assets/img/style-13.jpg',
    popularity: 80,
  },
  {
    id: 14,
    name: 'Stitch Cornrows',
    category: 'Cornrows',
    length: 'Medium',
    price: 170,
    duration: '3-4 hrs',
    rating: 4.6,
    reviews: 76,
    image: '/assets/img/style-14.jpg',
    popularity: 72,
  },

  // TWISTS
  {
    id: 15,
    name: 'Senegalese Twists',
    category: 'Twists',
    length: 'Long',
    price: 210,
    duration: '5-6 hrs',
    rating: 4.8,
    reviews: 167,
    image: '/assets/img/style-15.jpg',
    popularity: 85,
  },
  {
    id: 16,
    name: 'Havana Twists',
    category: 'Twists',
    length: 'Medium',
    price: 180,
    duration: '4-5 hrs',
    rating: 4.6,
    reviews: 93,
    image: '/assets/img/style-16.jpg',
    popularity: 72,
  },
  {
    id: 17,
    name: 'Spring Twists',
    category: 'Twists',
    length: 'Long',
    price: 230,
    duration: '5-6 hrs',
    rating: 4.7,
    reviews: 145,
    image: '/assets/img/wig-lf-04.jpg',
    popularity: 78,
  },

  // LOCS
  {
    id: 18,
    name: 'Dreadlocks',
    category: 'Locs',
    length: 'Long',
    price: 300,
    duration: '8-10 hrs',
    rating: 4.9,
    reviews: 245,
    image: '/assets/img/user-d.jpg',
    popularity: 88,
  },
  {
    id: 19,
    name: 'Sisterlocks',
    category: 'Locs',
    length: 'Long',
    price: 350,
    duration: '10-12 hrs',
    rating: 4.9,
    reviews: 189,
    image: '/assets/img/user-1.jpg',
    popularity: 85,
    isNew: true,
  },
  {
    id: 20,
    name: 'Faux Locs',
    category: 'Locs',
    length: 'Long',
    price: 260,
    duration: '6-7 hrs',
    rating: 4.8,
    reviews: 201,
    image: '/assets/img/user-2.jpg',
    popularity: 90,
    isTrending: true,
  },

  // GODDESS & PROTECTIVE
  {
    id: 21,
    name: 'Goddess Braids',
    category: 'Goddess & Protective',
    length: 'Long',
    price: 240,
    duration: '5-6 hrs',
    rating: 4.9,
    reviews: 178,
    image: '/assets/img/user-3.jpg',
    popularity: 92,
    isTrending: true,
  },
  {
    id: 22,
    name: 'Crochet Braids',
    category: 'Goddess & Protective',
    length: 'Medium',
    price: 150,
    duration: '3-4 hrs',
    rating: 4.4,
    reviews: 76,
    image: '/assets/img/user-4.jpg',
    popularity: 70,
  },
  {
    id: 23,
    name: 'Protective Style Updo',
    category: 'Goddess & Protective',
    length: 'Medium',
    price: 200,
    duration: '4-5 hrs',
    rating: 4.7,
    reviews: 112,
    image: '/assets/img/user-5.jpg',
    popularity: 78,
  },

  // CULTURAL & SPECIALTY
  {
    id: 24,
    name: 'Tribal Braids',
    category: 'Cultural & Specialty',
    length: 'Long',
    price: 250,
    duration: '5-6 hrs',
    rating: 4.8,
    reviews: 156,
    image: '/assets/img/user-a.jpg',
    popularity: 84,
    isTrending: true,
  },
  {
    id: 25,
    name: 'Beaded Braids',
    category: 'Cultural & Specialty',
    length: 'Long',
    price: 280,
    duration: '6-7 hrs',
    rating: 4.9,
    reviews: 134,
    image: '/assets/img/user-c.jpg',
    popularity: 86,
    isNew: true,
  },
];

// MARKETPLACE ITEMS - Wigs & Accessories
export const marketplaceItems = [
  {
    id: 'w1',
    name: 'Virgin Hair Wig - 24"',
    price: 450,
    rating: 4.9,
    reviews: 89,
    image: '/assets/img/wig-co-02-b.jpg',
    category: 'Wigs',
    description: '100% human hair, pre-plucked, bleached knots',
    isNew: true,
  },
  {
    id: 'w2',
    name: 'Lace Front Wig - 20"',
    price: 380,
    rating: 4.8,
    reviews: 67,
    image: '/assets/img/wig-co-03.jpg',
    category: 'Wigs',
    description: 'Swiss lace, 13x6 inch, natural hairline',
    isTrending: true,
  },
  {
    id: 'w3',
    name: 'Glueless Wig - 18"',
    price: 320,
    rating: 4.7,
    reviews: 54,
    image: '/assets/img/wig-fl-02-b.jpg',
    category: 'Wigs',
    description: 'Easy wear, comfortable, natural look',
  },
  {
    id: 'w4',
    name: 'Curly Texture Wig - 22"',
    price: 420,
    rating: 4.9,
    reviews: 73,
    image: '/assets/img/wig-cat-lf.jpg',
    category: 'Wigs',
    description: 'Bouncy curls, HD lace, pre-bleached knots',
    isNew: true,
    isTrending: true,
  },
  {
    id: 'w5',
    name: 'Straight Human Hair Wig - 26"',
    price: 550,
    rating: 4.9,
    reviews: 92,
    image: '/assets/img/wig-cat-sy.jpg',
    category: 'Wigs',
    description: 'Silky straight, 100% virgin hair',
    isTrending: true,
  },
  {
    id: 'w6',
    name: 'Bundles & Closure Set',
    price: 280,
    rating: 4.6,
    reviews: 45,
    image: '/assets/img/wig-cl-01-b.jpg',
    category: 'Hair Bundles',
    description: '3 bundles + 1 closure, 100% human hair',
  },
  {
    id: 'w7',
    name: 'Pre-stretched Braiding Hair',
    price: 45,
    rating: 4.5,
    reviews: 123,
    image: '/assets/img/wig-cl-01.jpg',
    category: 'Accessories',
    description: 'Kanekalon, 24 inches, 6 packs',
    isTrending: true,
  },
  {
    id: 'w8',
    name: 'Edge Control & Gel Kit',
    price: 35,
    rating: 4.4,
    reviews: 89,
    image: '/assets/img/wig-co-01-b.jpg',
    category: 'Accessories',
    description: 'Extra hold, non-flaking, 4oz + styling gel',
  },
];